CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "name" varchar(100),
  "profile_information" text,
  "settings_preferences" text,
  "authentication_details" text
);

CREATE TABLE "budgets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "month_year" varchar(7) NOT NULL,
  "total_amount" decimal(10,2) NOT NULL,
  "creation_date" datetime NOT NULL,
  "last_modified_date" datetime,
  "status" varchar(20)
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "description" text,
  "user_id" integer
);

CREATE TABLE "transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "budget_id" integer NOT NULL,
  "category_id" integer NOT NULL,
  "date" datetime NOT NULL,
  "item_description" text,
  "amount" decimal(10,2) NOT NULL,
  "currency" varchar(3) NOT NULL,
  "type" varchar(10) NOT NULL,
  "purpose" text,
  "status" varchar(20)
);

CREATE TABLE "ml_models" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "model_type" varchar(50) NOT NULL,
  "parameters" text,
  "accuracy_metrics" text,
  "creation_date" datetime NOT NULL,
  "last_used_date" datetime
);

COMMENT ON COLUMN "transactions"."type" IS 'debit/credit';

ALTER TABLE "budgets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("budget_id") REFERENCES "budgets" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "ml_models" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
