CREATE TABLE
    users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        uid VARCHAR(50) UNIQUE,
        email varchar(255) UNIQUE NOT NULL,
        first_name varchar(100) NOT NULL,
        last_name varchar(100) NOT NULL,
        password varchar(255) NOT NULL,
        status VARCHAR(20) DEFAULT 'PENDING',
        google_id VARCHAR(100) UNIQUE,
        google_token TEXT,
        auth_provider VARCHAR(20),
        profile_information text,
        settings_preferences text,
        authentication_details text,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
    );

-- Add indexes for better performance
CREATE INDEX idx_users_uid ON users (uid);

CREATE INDEX idx_users_google_id ON users (google_id)
WHERE
    google_id IS NOT NULL;

CREATE TABLE
    budgets (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id integer NOT NULL,
        month_year varchar(7) NOT NULL,
        total_amount decimal(10, 2) NOT NULL,
        creation_date TIMESTAMP NOT NULL,
        last_modified_date TIMESTAMP,
        status varchar(20),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
    );

CREATE TABLE
    categories (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(50) NOT NULL,
        description text,
        user_id integer,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
    );

CREATE TABLE
    transactions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        budget_id integer NOT NULL,
        category_id integer NOT NULL,
        date TIMESTAMP NOT NULL,
        item_description text,
        amount decimal(10, 2) NOT NULL,
        currency varchar(3) NOT NULL,
        type varchar(10) NOT NULL,
        purpose text,
        status varchar(20),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
    );

CREATE TABLE
    ml_models (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id integer NOT NULL,
        model_type varchar(50) NOT NULL,
        parameters text,
        metrics_name text,
        metrics_value text,
        last_used_date TIMESTAMP,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP
    );

COMMENT ON COLUMN transactions.type IS 'debit/credit';

COMMENT ON COLUMN users.uid IS 'Unique identifier for the user';

COMMENT ON COLUMN users.status IS 'Account status: PENDING, ACCEPTED, REJECTED';

COMMENT ON COLUMN users.google_id IS 'Google user ID for Google Sign-In';

COMMENT ON COLUMN users.google_token IS 'Google OAuth token information';

COMMENT ON COLUMN users.auth_provider IS 'Authentication provider: local, google, etc.';

ALTER TABLE budgets ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE categories ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE transactions ADD FOREIGN KEY (budget_id) REFERENCES budgets (id);

ALTER TABLE transactions ADD FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE ml_models ADD FOREIGN KEY (user_id) REFERENCES users (id);